### PR TITLE
Handle assigning 0 to pointers

### LINKED ISSUE #12: Allow assigning 0 to pointer types
C lets you to do this:

```c
int *a = 0;
```

`30cc` gives a type error. We should exceptionally allow assigning the value of `0` to pointer types. (Values greater than 0 should be prevented though)

### PR DESCRIPTION
**Pull request by Glyphack**
Fix: #12

### CODE REVIEW

File: codegen/codegen.c [hunk 1]
```diff
@@ -339,6 +339,17 @@ general_type *new_struct_type(char *struct_name)
 
 int types_equal(general_type *a, general_type *b, context *ctx)
 {
+    // Special case for handling assigning NULL to pointers
+    if (a->size == pointer_type_size)
```
Comment (amiremohamadi) [inline codegen/codegen.c]: just out of curiosity, why not checking `a->kind == TYPE_POINTER` here?

**Review by amiremohamadi — APPROVED** [review]

File: codegen/codegen.c (hunk 1 above)
Comment (Glyphack) [reply codegen/codegen.c]: I didn't know about that field :D just followed the code below let me change it.
